baseURL = "http://www.praneith.com" 
title = "praneith ranganath"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 6
enableEmoji = true

[services]
[services.disqus]
# Enable Disqus comments
# shortname = "yourdiscussshortname"

[markup.highlight]
noClasses = false

[params]
author = "Praneith Ranganath"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "My portfolio"
keywords = "blog,student,northeastern,personal"
info = ["Masters in Data Analytics", "Northeastern University", "Microsoft Azure AI Engineer Certified"]  
avatarURL = "images/IMG_5888.jpg"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2019
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/johndoe/johndoe.github.io/tree/"
# Right To Left, shift content direction for languages such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "light"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = true
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

[taxonomies]
category = "categories"
series = "series" 
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/P101010"

[[params.social]] 
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"  
weight = 2
url = "https://www.linkedin.com/in/praneithranganath10/"

[[params.social]]
name = "Medium"
icon = "fa-brands fa-medium fa-2x"
weight = 4  
url = "https://medium.com/@praneithranganath10"
rel = "me"
type = "text/html"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "Posts"
weight = 1
url = "posts/"

[[languages.en.menu.main]]
name = "Projects" 
weight = 2
url = "projects/"

[[languages.en.menu.main]]
name = "Resume"
weight = 3
url = "resume/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 4
url = "contact/"